import {
  Amelia,
  Charlotte,
  Daniel,
  David,
  Ethan,
  Henry,
  Isabella,
  James,
  Lucas,
  Mason,
  Mia,
  Michael,
  Olivia,
  Robert,
  Sophia,
  William,
  firstUser,
  seconduser,
} from "@/assets";

// Function to generate random views between min and max
const getRandomViews = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min + 1)) + min;

// Users array with random views added
export const Users = [
  {
    name: "David Willson",
    isVerified: false,
    image: David,
    connection: 1203,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Robert Brown",
    isVerified: true,
    image: Robert,
    connection: 566,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Daniel Lewis",
    isVerified: true,
    image: Daniel,
    connection: 705,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Alice Smith",
    isVerified: false,
    image: firstUser,
    connection: 15600,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Emma Johnson",
    isVerified: true,
    image: seconduser,
    connection: 1283,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Michael Davis",
    isVerified: false,
    image: Michael,
    connection: 12,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Olivia Martinez",
    isVerified: true,
    image: Olivia,
    connection: 984,
    views: getRandomViews(100, 10000),
  },
  {
    name: "James Anderson",
    isVerified: true,
    image: James,
    connection: 1734,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Sophia Lee",
    isVerified: false,
    image: Sophia,
    connection: 289,
    views: getRandomViews(100, 10000),
  },
  {
    name: "William Garcia",
    isVerified: true,
    image: William,
    connection: 875,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Mia Rodriguez",
    isVerified: false,
    image: Mia,
    connection: 432,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Ethan Wilson",
    isVerified: true,
    image: Ethan,
    connection: 620,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Isabella Martinez",
    isVerified: true,
    image: Isabella,
    connection: 1472,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Henry Walker",
    isVerified: false,
    image: Henry,
    connection: 78,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Charlotte Harris",
    isVerified: true,
    image: Charlotte,
    connection: 953,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Lucas Clark",
    isVerified: true,
    image: Lucas,
    connection: 1160,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Amelia Lewis",
    isVerified: false,
    image: Amelia,
    connection: 520,
    views: getRandomViews(100, 10000),
  },
  {
    name: "Mason Robinson",
    isVerified: true,
    image: Mason,
    connection: 1347,
    views: getRandomViews(100, 10000),
  },
];
